services:
  riscv:
    image: ghcr.io/tbthub/riscv:latest
    container_name: risc
    volumes:
      - ./:/risc
    working_dir: /risc
    command: bash
    cpus: '1'
    restart: unless-stopped
    stdin_open: true
    tty: true
