version: '3.8'
services:
  riscv:
    image: bwtang/xv6-env
    container_name: risc_vfs
    volumes:
      - ./:/risc
    working_dir: /risc
    command: bash
    cpus: '1'  # 限制最多使用 1 个 CPU 的算力
    stdin_open: true
    tty: true
